// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'mls_sync_state.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'rejoin_reason.dart';
import 'user.dart';
import 'user_address.dart';
import 'user_key.dart';
import 'user_state.dart';
part 'app_event.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
sealed class AppEvent with _$AppEvent {
  const AppEvent._();

  const factory AppEvent.userStateChanged(UserState field0) =
      AppEvent_UserStateChanged;
  const factory AppEvent.connectionChanged({required bool connected}) =
      AppEvent_ConnectionChanged;
  const factory AppEvent.error({required String message}) = AppEvent_Error;
  const factory AppEvent.mlsGroupUpdated({
    required String roomId,
    required String key,
    required BigInt epoch,
  }) = AppEvent_MlsGroupUpdated;
  const factory AppEvent.mlsSyncStateChanged({
    required MlsSyncState state,
    RejoinReason? reason,
  }) = AppEvent_MlsSyncStateChanged;
}
