// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// Event action type indicating what happened to the model
enum EventAction {
  /// When the model has been deleted since the last event loop poll
  delete,

  /// When the model has been created since the last event loop poll
  create,

  /// When the model was already known by the client before the last event loop poll
  /// and was updated since the last event loop poll
  update,

  /// When the model was already known by the client before the last event loop poll
  /// and only its metadata were updated since the last event loop poll
  updateFlags,
}

/// Response for get_events API call
class FrbGetEventsResponse {
  /// Meeting events (ID and Action) if any
  final List<FrbMeetingEventItem>? meetingEvents;

  /// Whether there are more events available
  final bool more;

  /// Whether a full refresh is needed
  final bool refresh;

  /// The new event ID
  final String eventId;

  const FrbGetEventsResponse({
    this.meetingEvents,
    required this.more,
    required this.refresh,
    required this.eventId,
  });

  @override
  int get hashCode =>
      meetingEvents.hashCode ^
      more.hashCode ^
      refresh.hashCode ^
      eventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbGetEventsResponse &&
          runtimeType == other.runtimeType &&
          meetingEvents == other.meetingEvents &&
          more == other.more &&
          refresh == other.refresh &&
          eventId == other.eventId;
}

/// Meeting event item containing ID and action
class FrbMeetingEventItem {
  /// Meeting ID
  final String id;

  /// Action that occurred
  final EventAction action;

  const FrbMeetingEventItem({required this.id, required this.action});

  @override
  int get hashCode => id.hashCode ^ action.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMeetingEventItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action;
}
