// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

class FrbMeetingInfo {
  /// Unique meeting link name
  final String meetingLinkName;

  /// Encrypted meeting name with session key
  final String meetingName;

  /// Salt of the password
  final String salt;

  /// Encrypted session key of the meeting
  final String sessionKey;

  /// 1 if meeting is locked
  final int locked;

  /// Maximum duration of this meeting in seconds
  final int maxDuration;

  /// Maximum number of participants allowed in this meeting
  final int maxParticipants;

  /// The datetime when the meeting room will be forcefully terminated
  final PlatformInt64? expirationTime;

  const FrbMeetingInfo({
    required this.meetingLinkName,
    required this.meetingName,
    required this.salt,
    required this.sessionKey,
    required this.locked,
    required this.maxDuration,
    required this.maxParticipants,
    this.expirationTime,
  });

  @override
  int get hashCode =>
      meetingLinkName.hashCode ^
      meetingName.hashCode ^
      salt.hashCode ^
      sessionKey.hashCode ^
      locked.hashCode ^
      maxDuration.hashCode ^
      maxParticipants.hashCode ^
      expirationTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMeetingInfo &&
          runtimeType == other.runtimeType &&
          meetingLinkName == other.meetingLinkName &&
          meetingName == other.meetingName &&
          salt == other.salt &&
          sessionKey == other.sessionKey &&
          locked == other.locked &&
          maxDuration == other.maxDuration &&
          maxParticipants == other.maxParticipants &&
          expirationTime == other.expirationTime;
}
