// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MeetChatMessage {
  final String id;
  final PlatformInt64 timestamp;
  final String identity;
  final String name;
  final bool seen;
  final String message;

  const MeetChatMessage({
    required this.id,
    required this.timestamp,
    required this.identity,
    required this.name,
    required this.seen,
    required this.message,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      timestamp.hashCode ^
      identity.hashCode ^
      name.hashCode ^
      seen.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          timestamp == other.timestamp &&
          identity == other.identity &&
          name == other.name &&
          seen == other.seen &&
          message == other.message;
}
