// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MeetLink {
  final String id;
  final String pwd;

  const MeetLink({required this.id, required this.pwd});

  @override
  int get hashCode => id.hashCode ^ pwd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetLink &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pwd == other.pwd;
}
