// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MeetParticipant {
  final String participantUuid;
  final String displayName;
  final String? encryptedDisplayName;
  final int? canSubscribe;
  final int? canPublish;
  final int? canPublishData;
  final int? isAdmin;
  final int? isHost;

  const MeetParticipant({
    required this.participantUuid,
    required this.displayName,
    this.encryptedDisplayName,
    this.canSubscribe,
    this.canPublish,
    this.canPublishData,
    this.isAdmin,
    this.isHost,
  });

  @override
  int get hashCode =>
      participantUuid.hashCode ^
      displayName.hashCode ^
      encryptedDisplayName.hashCode ^
      canSubscribe.hashCode ^
      canPublish.hashCode ^
      canPublishData.hashCode ^
      isAdmin.hashCode ^
      isHost.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeetParticipant &&
          runtimeType == other.runtimeType &&
          participantUuid == other.participantUuid &&
          displayName == other.displayName &&
          encryptedDisplayName == other.encryptedDisplayName &&
          canSubscribe == other.canSubscribe &&
          canPublish == other.canPublish &&
          canPublishData == other.canPublishData &&
          isAdmin == other.isAdmin &&
          isHost == other.isHost;
}
