// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// FFI-friendly version of MeetInfo
class FrbMeetInfo {
  final String meetName;
  final String meetLinkName;
  final String accessToken;
  final String websocketUrl;
  final int participantsCount;
  final bool isLocked;
  final int maxDuration;
  final int maxParticipants;

  /// Unix timestamp in seconds (Option<i64>)
  final PlatformInt64? expirationTime;

  const FrbMeetInfo({
    required this.meetName,
    required this.meetLinkName,
    required this.accessToken,
    required this.websocketUrl,
    required this.participantsCount,
    required this.isLocked,
    required this.maxDuration,
    required this.maxParticipants,
    this.expirationTime,
  });

  @override
  int get hashCode =>
      meetName.hashCode ^
      meetLinkName.hashCode ^
      accessToken.hashCode ^
      websocketUrl.hashCode ^
      participantsCount.hashCode ^
      isLocked.hashCode ^
      maxDuration.hashCode ^
      maxParticipants.hashCode ^
      expirationTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMeetInfo &&
          runtimeType == other.runtimeType &&
          meetName == other.meetName &&
          meetLinkName == other.meetLinkName &&
          accessToken == other.accessToken &&
          websocketUrl == other.websocketUrl &&
          participantsCount == other.participantsCount &&
          isLocked == other.isLocked &&
          maxDuration == other.maxDuration &&
          maxParticipants == other.maxParticipants &&
          expirationTime == other.expirationTime;
}
