// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

class FrbParticipantTrackSettings {
  final int audio;
  final int video;

  const FrbParticipantTrackSettings({required this.audio, required this.video});

  @override
  int get hashCode => audio.hashCode ^ video.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbParticipantTrackSettings &&
          runtimeType == other.runtimeType &&
          audio == other.audio &&
          video == other.video;
}
