// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_user_data_and_auth`

class ProtonUserSession {
  final String userId;
  final String userMail;
  final String userName;
  final String? userDisplayName;
  final String sessionId;
  final String accessToken;
  final String refreshToken;
  final List<String> scopes;
  final String userKeyId;
  final String userPrivateKey;
  final String userPassphrase;

  const ProtonUserSession({
    required this.userId,
    required this.userMail,
    required this.userName,
    this.userDisplayName,
    required this.sessionId,
    required this.accessToken,
    required this.refreshToken,
    required this.scopes,
    required this.userKeyId,
    required this.userPrivateKey,
    required this.userPassphrase,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      userMail.hashCode ^
      userName.hashCode ^
      userDisplayName.hashCode ^
      sessionId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      scopes.hashCode ^
      userKeyId.hashCode ^
      userPrivateKey.hashCode ^
      userPassphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtonUserSession &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          userMail == other.userMail &&
          userName == other.userName &&
          userDisplayName == other.userDisplayName &&
          sessionId == other.sessionId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          scopes == other.scopes &&
          userKeyId == other.userKeyId &&
          userPrivateKey == other.userPrivateKey &&
          userPassphrase == other.userPassphrase;
}
