// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'recurrence_frequency.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class ScheduleMeetingRequest {
  final String title;
  final PlatformInt64 startTimestamp;
  final PlatformInt64 endTimestamp;
  final RecurrenceFrequency? recurrence;
  final String? location;
  final String? description;
  final String? timeZone;

  const ScheduleMeetingRequest({
    required this.title,
    required this.startTimestamp,
    required this.endTimestamp,
    this.recurrence,
    this.location,
    this.description,
    this.timeZone,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      startTimestamp.hashCode ^
      endTimestamp.hashCode ^
      recurrence.hashCode ^
      location.hashCode ^
      description.hashCode ^
      timeZone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleMeetingRequest &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          startTimestamp == other.startTimestamp &&
          endTimestamp == other.endTimestamp &&
          recurrence == other.recurrence &&
          location == other.location &&
          description == other.description &&
          timeZone == other.timeZone;
}
