// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'meeting_type.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

class FrbUpcomingMeeting {
  final String id;
  final String? addressId;
  final String meetingLinkName;
  final String meetingName;
  final String meetingPassword;
  final MeetingType meetingType;
  final PlatformInt64? startTime;
  final PlatformInt64? endTime;
  final String? rRule;
  final String? timeZone;
  final String? calendarId;
  final int protonCalendar;
  final PlatformInt64? createTime;
  final PlatformInt64? lastUsedTime;
  final String? calendarEventId;

  const FrbUpcomingMeeting({
    required this.id,
    this.addressId,
    required this.meetingLinkName,
    required this.meetingName,
    required this.meetingPassword,
    required this.meetingType,
    this.startTime,
    this.endTime,
    this.rRule,
    this.timeZone,
    this.calendarId,
    required this.protonCalendar,
    this.createTime,
    this.lastUsedTime,
    this.calendarEventId,
  });

  static FrbUpcomingMeeting defaultValues() => RustLib.instance.api
      .crateProtonMeetModelsUpcomingMeetingFrbUpcomingMeetingDefaultValues();

  static FrbUpcomingMeeting newForJoin({
    required String meetingLinkName,
    required String meetingPassword,
  }) => RustLib.instance.api
      .crateProtonMeetModelsUpcomingMeetingFrbUpcomingMeetingNewForJoin(
        meetingLinkName: meetingLinkName,
        meetingPassword: meetingPassword,
      );

  @override
  int get hashCode =>
      id.hashCode ^
      addressId.hashCode ^
      meetingLinkName.hashCode ^
      meetingName.hashCode ^
      meetingPassword.hashCode ^
      meetingType.hashCode ^
      startTime.hashCode ^
      endTime.hashCode ^
      rRule.hashCode ^
      timeZone.hashCode ^
      calendarId.hashCode ^
      protonCalendar.hashCode ^
      createTime.hashCode ^
      lastUsedTime.hashCode ^
      calendarEventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbUpcomingMeeting &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          addressId == other.addressId &&
          meetingLinkName == other.meetingLinkName &&
          meetingName == other.meetingName &&
          meetingPassword == other.meetingPassword &&
          meetingType == other.meetingType &&
          startTime == other.startTime &&
          endTime == other.endTime &&
          rRule == other.rRule &&
          timeZone == other.timeZone &&
          calendarId == other.calendarId &&
          protonCalendar == other.protonCalendar &&
          createTime == other.createTime &&
          lastUsedTime == other.lastUsedTime &&
          calendarEventId == other.calendarEventId;
}
