// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ProtonUserKey {
  final String id;
  final int version;
  final String privateKey;
  final String? recoverySecret;
  final String? recoverySecretSignature;
  final String? token;
  final String fingerprint;
  final String? signature;
  final int primary;
  final int active;

  const ProtonUserKey({
    required this.id,
    required this.version,
    required this.privateKey,
    this.recoverySecret,
    this.recoverySecretSignature,
    this.token,
    required this.fingerprint,
    this.signature,
    required this.primary,
    required this.active,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      version.hashCode ^
      privateKey.hashCode ^
      recoverySecret.hashCode ^
      recoverySecretSignature.hashCode ^
      token.hashCode ^
      fingerprint.hashCode ^
      signature.hashCode ^
      primary.hashCode ^
      active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtonUserKey &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          version == other.version &&
          privateKey == other.privateKey &&
          recoverySecret == other.recoverySecret &&
          recoverySecretSignature == other.recoverySecretSignature &&
          token == other.token &&
          fingerprint == other.fingerprint &&
          signature == other.signature &&
          primary == other.primary &&
          active == other.active;
}
