// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'user.dart';
import 'user_address.dart';
import 'user_key.dart';

class UserState {
  final ProtonUser userData;
  final List<ProtonUserKey> userKeys;
  final List<Address> userAddresses;

  const UserState({
    required this.userData,
    required this.userKeys,
    required this.userAddresses,
  });

  @override
  int get hashCode =>
      userData.hashCode ^ userKeys.hashCode ^ userAddresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserState &&
          runtimeType == other.runtimeType &&
          userData == other.userData &&
          userKeys == other.userKeys &&
          userAddresses == other.userAddresses;
}
