// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'user_key.dart';

class Address {
  /// The address's ID.
  final String id;

  /// The address itself.
  final String email;

  /// The address's keys.
  final List<ProtonUserKey> keys;

  const Address({required this.id, required this.email, required this.keys});

  @override
  int get hashCode => id.hashCode ^ email.hashCode ^ keys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Address &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email &&
          keys == other.keys;
}
