// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../errors.dart';
import '../frb_generated.dart';
import 'meet_auth_store.dart';
import 'models/app_event.dart';
import 'models/connection_state.dart';
import 'models/event.dart';
import 'models/join_type.dart';
import 'models/meet_chat_message.dart';
import 'models/meet_info.dart';
import 'models/meet_link.dart';
import 'models/meet_participant.dart';
import 'models/meeting_info.dart';
import 'models/meeting_type.dart';
import 'models/mls_sync_state.dart';
import 'models/participant_track_settings.dart';
import 'models/proton_user_session.dart';
import 'models/recurrence_frequency.dart';
import 'models/rejoin_reason.dart';
import 'models/schedule_meeting.dart';
import 'models/unleash_response.dart';
import 'models/upcoming_meeting.dart';
import 'models/user.dart';
import 'models/user_address.dart';
import 'models/user_key.dart';
import 'models/user_state.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage/user_key_provider.dart';
import 'user_config.dart';

// These functions are ignored because they are not marked as `pub`: `compute_mailbox_password`, `get_app_core_runtime_handle`, `spawn_on_background`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MEET_LIVEKIT_ADMIN_CHANGE_DART_CALLBACK`, `MEET_MLS_GROUP_UPDATE_DART_CALLBACK`, `MEET_MLS_SYNC_STATE_UPDATE_DART_CALLBACK`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `update_display_name`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppCore>>
abstract class AppCore implements RustOpaqueInterface {
  Future<void> clearLivekitAdminChangeCallback();

  Future<void> clearMlsGroupUpdateCallback();

  Future<void> clearMlsSyncStateUpdateCallback();

  Future<FrbUpcomingMeeting> createMeeting({
    required String meetingName,
    required bool hasSession,
    required MeetingType meetingType,
    String? customPassword,
    PlatformInt64? startTime,
    PlatformInt64? endTime,
    String? timeZone,
    String? rRule,
  });

  Future<FrbUpcomingMeeting> createPersonalMeeting({
    required String meetingName,
    String? customPassword,
    required bool isRotate,
  });

  Future<(String, String)> decryptMessage({required List<int> data});

  Future<void> deleteMeeting({required String meetingName});

  Future<FrbUpcomingMeeting> editMeetingName({
    required String meetingId,
    required String newMeetingName,
    required String meetingPassword,
  });

  Future<Uint8List> encryptMessage({required String message});

  Future<void> endMeeting();

  Future<String> exportScheduleMeetingToIcs({
    required ScheduleMeetingRequest meeting,
  });

  Future<UnleashResponse> fetchToggles();

  Future<UserState> fetchUserState({required String userId});

  /// Fork selector for creating child sessions (e.g., for account deletion)
  /// Returns a selector string that can be used to create a fork session
  /// Client must be authenticated first
  Future<String> forkSelector({required String clientChild});

  /// Get events starting from a given event ID
  /// Returns GetEventsResponse containing meeting events, flags, and new event ID
  Future<FrbGetEventsResponse> getEvents({required String eventId});

  Future<String> getGroupDisplayCode();

  Future<(String, BigInt)> getGroupKey();

  Future<int> getGroupLen();

  Future<JoinType> getJoinType({
    required bool isNewJoinType,
    required bool enableJoinTypeSwitch,
    required int currentParticipantCount,
  });

  /// Get the latest event ID from the server
  Future<String> getLatestEventId();

  Future<FrbMeetingInfo> getMeetingInfo({required String meetingLinkName});

  Future<List<MeetParticipant>> getParticipants({required String meetLinkName});

  Future<int> getParticipantsCount({required String meetLinkName});

  Future<List<FrbUpcomingMeeting>> getUpcomingMeetings();

  Future<ProtonUser> getUser({required String userId});

  Future<UserConfig> getUserConfig();

  Future<ConnectionState> getWsState();

  Future<bool> isMlsUpToDate();

  Future<bool> isWebsocketHasReconnected();

  Future<FrbMeetInfo> joinMeeting({
    required String meetLinkName,
    required String meetLinkPassword,
    required String displayName,
    String? sessionId,
    required bool isMeetNewJoinType,
    required bool isMeetSwitchJoinType,
    required bool reuseToken,
    required bool usePsk,
  });

  Future<void> joinMeetingWithAccessToken({
    required String accessToken,
    required String meetLinkName,
    required String meetingPassword,
    required bool usePsk,
    String? sessionId,
  });

  Future<void> joinMeetingWithAccessTokenWithProposal({
    required String accessToken,
    required String meetLinkName,
    required String meetingPassword,
    required bool usePsk,
    String? sessionId,
  });

  Future<void> leaveRoom();

  Future<void> lockMeeting({required String meetLinkName});

  /// Log metrics when connection is lost
  Future<void> logConnectionLost();

  /// Log metrics when room join is successful, this method must be called right after the room is showing to user on client side
  Future<void> logJoinedRoom({
    bool? isVp9DecodeSupported,
    bool? isVp9EncodeSupported,
  });

  /// Log metrics when room join fails, this method must be called right after the room join fails on client side
  Future<void> logJoinedRoomFailed({String? errorCode});

  /// Log metrics when connection is lost
  Future<void> logUserEpochHealth({
    required int currentEpoch,
    required String epochDisplayCode,
  });

  /// Log user rejoin metrics, parameters will be passed from client side
  Future<void> logUserRejoin({
    required BigInt rejoinTimeMs,
    required int incrementalCount,
    required RejoinReason reason,
    required bool success,
  });

  Future<ProtonUserSession> login({
    required String username,
    required String password,
  });

  Future<ProtonUserSession> loginWithTwoFactor({
    required String password,
    required String twoFactorCode,
  });

  Future<void> logout({required String userId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AppCore> newInstance({
    required String env,
    required String appVersion,
    required String userAgent,
    required String dbPath,
    required ProtonMeetAuthStore authStore,
    required String wsHost,
    required String httpHost,
    UserState? userState,
    required FrbUserKeyProvider userKeyProvider,
  }) => RustLib.instance.api.crateProtonMeetCoreAppCoreNew(
    env: env,
    appVersion: appVersion,
    userAgent: userAgent,
    dbPath: dbPath,
    authStore: authStore,
    wsHost: wsHost,
    httpHost: httpHost,
    userState: userState,
    userKeyProvider: userKeyProvider,
  );

  Future<MeetChatMessage> parseChatMessage({required String chatMessage});

  static Future<MeetLink?> parseMeetingLink({required String link}) => RustLib
      .instance
      .api
      .crateProtonMeetCoreAppCoreParseMeetingLink(link: link);

  /// Lightweight server reachability check (e.g. when logged out). Surfaces API errors such as force upgrade.
  Future<BigInt> ping();

  Future<void> removeParticipant({required String participantUuid});

  Future<void> setLivekitActiveUuids({required List<String> activeUuids});

  Future<void> setLivekitAdminChangeCallback({
    required FutureOr<void> Function(String, String, int) callback,
  });

  Future<void> setMlsGroupUpdateCallback({
    required FutureOr<void> Function(String) callback,
  });

  Future<void> setMlsSyncStateUpdateCallback({
    required FutureOr<void> Function(MlsSyncState, RejoinReason?) callback,
  });

  /// Set WebSocket max ping failures (None to use default)
  /// This is particularly useful for Safari when it goes to background, allowing more tolerance
  Future<void> setWebsocketMaxPingFailures({int? failures});

  /// Set WebSocket ping interval in seconds (None to use default)
  Future<void> setWebsocketPingInterval({BigInt? seconds});

  /// Set WebSocket pong timeout in seconds (None to use default)
  Future<void> setWebsocketPongTimeout({BigInt? seconds});

  Stream<AppEvent> subscribeEvents();

  /// Manually trigger WebSocket reconnection.
  /// Call this when network connectivity changes (e.g., WiFi → cellular, airplane mode off).
  Future<void> triggerWebsocketReconnect();

  Future<void> tryLogDesignatedCommitter({required int epoch});

  Future<void> unlockMeeting({required String meetLinkName});

  Future<void> updateAuth({
    required String userId,
    required String uid,
    required String access,
    required String refresh,
    required List<String> scopes,
  });

  Future<void> updateCameraMaxBitrate({
    required VideoMaxBitrate cameraMaxBitrate,
  });

  Future<void> updateCameraResolution({
    required VideoResolution cameraResolution,
  });

  Future<void> updateDarkMode({required bool darkMode});

  Future<void> updateLivekitAccessToken({required String accessToken});

  Future<void> updateLivekitAccessTokenAndWebsocketUrl({
    required String accessToken,
    required String websocketUrl,
  });

  Future<FrbUpcomingMeeting> updateMeetingSchedule({
    required String meetingId,
    required String meetingName,
    required String meetingPassword,
    PlatformInt64? startTime,
    PlatformInt64? endTime,
    String? timeZone,
    String? rRule,
  });

  Future<FrbParticipantTrackSettings> updateParticipantTrackSettings({
    required String participantUuid,
    int? audio,
    int? video,
  });

  Future<void> updateScreensharingMaxBitrate({
    required VideoMaxBitrate screensharingMaxBitrate,
  });

  Future<void> updateScreensharingResolution({
    required VideoResolution screensharingResolution,
  });

  Future<void> updateShowSelfTile({required bool showSelfTile});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MeetCoreError>>
abstract class MeetCoreError implements RustOpaqueInterface {}
