// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../errors.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_auth`, `refresh_auth_credential`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MEET_AUTH_STORE_DART_CALLBACK`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `env`, `fmt`, `fmt`, `get_auth`, `initialize`, `set_auth`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `logout`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProtonMeetAuthStore>>
abstract class ProtonMeetAuthStore implements RustOpaqueInterface {
  Future<void> clearAuthDartCallback();

  static ProtonMeetAuthStore fromSession({
    required String env,
    required String userId,
    required String uid,
    required String access,
    required String refresh,
    required List<String> scopes,
  }) => RustLib.instance.api
      .crateProtonMeetMeetAuthStoreProtonMeetAuthStoreFromSession(
        env: env,
        userId: userId,
        uid: uid,
        access: access,
        refresh: refresh,
        scopes: scopes,
      );

  factory ProtonMeetAuthStore({required String env}) => RustLib.instance.api
      .crateProtonMeetMeetAuthStoreProtonMeetAuthStoreNew(env: env);

  Future<void> setAuth({
    required String userId,
    required String uid,
    required String access,
    required String refresh,
    required List<String> scopes,
  });

  Future<void> setAuthDartCallback({
    required FutureOr<String> Function(ChildAuthSession) callback,
  });
}

class ChildAuthSession {
  final String sessionId;
  final String accessToken;
  final String refreshToken;
  final List<String> scopes;
  final String userId;

  const ChildAuthSession({
    required this.sessionId,
    required this.accessToken,
    required this.refreshToken,
    required this.scopes,
    required this.userId,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      accessToken.hashCode ^
      refreshToken.hashCode ^
      scopes.hashCode ^
      userId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChildAuthSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          scopes == other.scopes &&
          userId == other.userId;
}
