// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../errors.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> saveConfig({required UserConfig userConfig}) => RustLib
    .instance
    .api
    .crateProtonMeetUserConfigSaveConfig(userConfig: userConfig);

Future<UserConfig> loadConfig() =>
    RustLib.instance.api.crateProtonMeetUserConfigLoadConfig();

class UserConfig {
  final String displayName;
  final bool showSelfTile;
  final bool darkMode;
  final VideoResolution cameraResolution;
  final VideoMaxBitrate cameraMaxBitrate;
  final VideoResolution screensharingResolution;
  final VideoMaxBitrate screensharingMaxBitrate;

  const UserConfig({
    required this.displayName,
    required this.showSelfTile,
    required this.darkMode,
    required this.cameraResolution,
    required this.cameraMaxBitrate,
    required this.screensharingResolution,
    required this.screensharingMaxBitrate,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^
      showSelfTile.hashCode ^
      darkMode.hashCode ^
      cameraResolution.hashCode ^
      cameraMaxBitrate.hashCode ^
      screensharingResolution.hashCode ^
      screensharingMaxBitrate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserConfig &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          showSelfTile == other.showSelfTile &&
          darkMode == other.darkMode &&
          cameraResolution == other.cameraResolution &&
          cameraMaxBitrate == other.cameraMaxBitrate &&
          screensharingResolution == other.screensharingResolution &&
          screensharingMaxBitrate == other.screensharingMaxBitrate;
}

enum VideoMaxBitrate {
  kbps2000,
  kbps1900,
  kbps1800,
  kbps1700,
  kbps1600,
  kbps1500,
  kbps1400,
  kbps1300,
  kbps1200,
  kbps1100,
  kbps1000,
  kbps900,
  kbps800,
  kbps700,
  kbps600,
  kbps500,
  kbps400,
  kbps300,
  kbps200,
  kbps100,
}

enum VideoResolution { p360, p720, p1080, p4K }
