// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/user.dart';
import 'models/user_key.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Check if user has paid Mail subscription
bool hasPaidMail({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionHasPaidMail(user: user);

/// Check if user has paid Drive subscription
bool hasPaidDrive({required ProtonUser user}) => RustLib.instance.api
    .crateProtonMeetUserSubscriptionHasPaidDrive(user: user);

/// Check if user has paid Wallet subscription
bool hasPaidWallet({required ProtonUser user}) => RustLib.instance.api
    .crateProtonMeetUserSubscriptionHasPaidWallet(user: user);

/// Check if user has paid VPN subscription
bool hasPaidVpn({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionHasPaidVpn(user: user);

/// Check if user has Pass lifetime flag
bool hasPassLifetime({required ProtonUser user}) => RustLib.instance.api
    .crateProtonMeetUserSubscriptionHasPassLifetime(user: user);

/// Check if user has Pass via SimpleLogin flag
bool hasPassViaSimpleLogin({required ProtonUser user}) => RustLib.instance.api
    .crateProtonMeetUserSubscriptionHasPassViaSimpleLogin(user: user);

/// Check if user has paid Pass subscription (including lifetime or SimpleLogin)
bool hasPaidPass({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionHasPaidPass(user: user);

/// Check if user has Pass lifetime or via SimpleLogin
bool hasPassLifetimeOrViaSimpleLogin({required ProtonUser user}) => RustLib
    .instance
    .api
    .crateProtonMeetUserSubscriptionHasPassLifetimeOrViaSimpleLogin(user: user);

/// Check if user has paid Lumo subscription
bool hasPaidLumo({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionHasPaidLumo(user: user);

/// Check if user has paid Meet subscription
bool hasPaidMeet({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionHasPaidMeet(user: user);

/// Check if user is paid (has any subscription)
bool isPaid({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionIsPaid(user: user);

/// Check if user is private
bool isPrivate({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionIsPrivate(user: user);

/// Check if user is free (no subscription)
bool isFree({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionIsFree(user: user);

/// Check if user is admin
bool isAdmin({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionIsAdmin(user: user);

/// Check if user is member
bool isMember({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionIsMember(user: user);

/// Check if user is self (not delegated access)
bool isSelf({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionIsSelf(user: user);

/// Check if user is delinquent
bool isDelinquent({required ProtonUser user}) => RustLib.instance.api
    .crateProtonMeetUserSubscriptionIsDelinquent(user: user);

/// Check if user can pay (admin or free role)
bool canPay({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionCanPay(user: user);

/// Get user byte from base64url encoded user ID
int? getUserByte({required ProtonUser user}) =>
    RustLib.instance.api.crateProtonMeetUserSubscriptionGetUserByte(user: user);
