// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'errors.freezed.dart';

@freezed
sealed class BridgeError with _$BridgeError implements FrbException {
  const BridgeError._();

  const factory BridgeError.mutexLock(String field0) = BridgeError_MutexLock;
  const factory BridgeError.meetCore(String field0) = BridgeError_MeetCore;
  const factory BridgeError.missingTwoFactor() = BridgeError_MissingTwoFactor;
  const factory BridgeError.meetCoreAny(String field0) =
      BridgeError_MeetCoreAny;
  const factory BridgeError.login(String field0) = BridgeError_Login;
  const factory BridgeError.apiLock(String field0) = BridgeError_ApiLock;
  const factory BridgeError.accessToken(String field0) =
      BridgeError_AccessToken;

  /// Muon auth session error
  const factory BridgeError.muonAuthSession(String field0) =
      BridgeError_MuonAuthSession;

  /// Muon auth refresh error
  const factory BridgeError.muonAuthRefresh(String field0) =
      BridgeError_MuonAuthRefresh;

  /// Muon client error
  const factory BridgeError.muonClient(String field0) = BridgeError_MuonClient;

  /// Muon session error
  const factory BridgeError.muonSession(String field0) =
      BridgeError_MuonSession;

  /// Fork error
  const factory BridgeError.fork(String field0) = BridgeError_Fork;
  const factory BridgeError.encoding(String field0) = BridgeError_Encoding;
  const factory BridgeError.parseError(String field0) = BridgeError_ParseError;
  const factory BridgeError.std(String field0) = BridgeError_Std;
  const factory BridgeError.tracingsSubscriber(String field0) =
      BridgeError_TracingsSubscriber;
  const factory BridgeError.meetLink(String field0) = BridgeError_MeetLink;
  const factory BridgeError.chat(String field0) = BridgeError_Chat;
  const factory BridgeError.taskJoin(String field0) = BridgeError_TaskJoin;

  /// api response error
  const factory BridgeError.apiResponse(ResponseError field0) =
      BridgeError_ApiResponse;

  /// Meeting locked error (error code 2502)
  const factory BridgeError.meetingLocked() = BridgeError_MeetingLocked;
}

class ResponseError {
  final int code;
  final String error;
  final String details;

  const ResponseError({
    required this.code,
    required this.error,
    required this.details,
  });

  @override
  int get hashCode => code.hashCode ^ error.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResponseError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          error == other.error &&
          details == other.details;
}
