// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MEET_DART_LOGGER_CALLBACK`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `from`, `initialize`, `on_event`

Future<void> setFlutterLogCallback({
  required FutureOr<void> Function(RustLevel, String) callback,
}) => RustLib.instance.api.crateFlutterLoggerSetFlutterLogCallback(
  callback: callback,
);

class FlutterLogLayer {
  const FlutterLogLayer();

  static Future<FlutterLogLayer> default_() =>
      RustLib.instance.api.crateFlutterLoggerFlutterLogLayerDefault();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterLogLayer && runtimeType == other.runtimeType;
}

enum RustLevel {
  trace,
  debug,
  info,
  warn,
  error,
  unknown;

  static Future<RustLevel> fromStringRef({required String level}) => RustLib
      .instance
      .api
      .crateFlutterLoggerRustLevelFromStringRef(level: level);

  Future<String> toStr() =>
      RustLib.instance.api.crateFlutterLoggerRustLevelToStr(that: this);
}
