// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';
import 'errors.dart';
import 'flutter_logger.dart';
import 'frb_generated.dart';
import 'logger.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'panic_hook.dart';
import 'proton_meet/core.dart';
import 'proton_meet/meet_auth_store.dart';
import 'proton_meet/models/app_event.dart';
import 'proton_meet/models/connection_state.dart';
import 'proton_meet/models/event.dart';
import 'proton_meet/models/join_type.dart';
import 'proton_meet/models/meet_chat_message.dart';
import 'proton_meet/models/meet_info.dart';
import 'proton_meet/models/meet_link.dart';
import 'proton_meet/models/meet_participant.dart';
import 'proton_meet/models/meeting_info.dart';
import 'proton_meet/models/meeting_type.dart';
import 'proton_meet/models/mls_sync_state.dart';
import 'proton_meet/models/participant_track_settings.dart';
import 'proton_meet/models/proton_user_session.dart';
import 'proton_meet/models/recurrence_frequency.dart';
import 'proton_meet/models/rejoin_reason.dart';
import 'proton_meet/models/schedule_meeting.dart';
import 'proton_meet/models/unleash_response.dart';
import 'proton_meet/models/upcoming_meeting.dart';
import 'proton_meet/models/user.dart';
import 'proton_meet/models/user_address.dart';
import 'proton_meet/models/user_key.dart';
import 'proton_meet/models/user_state.dart';
import 'proton_meet/storage/user_key_provider.dart';
import 'proton_meet/token.dart';
import 'proton_meet/user_config.dart';
import 'proton_meet/user_subscription.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppCorePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FrbUserKeyProviderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MeetCoreErrorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ProtonMeetAuthStorePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RotatingFileWriterPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AppCore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    dynamic raw,
  );

  @protected
  FrbUserKeyProvider
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    dynamic raw,
  );

  @protected
  MeetCoreError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    dynamic raw,
  );

  @protected
  ProtonMeetAuthStore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    dynamic raw,
  );

  @protected
  RotatingFileWriter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    dynamic raw,
  );

  @protected
  AppCore
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    dynamic raw,
  );

  @protected
  FrbUserKeyProvider
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    dynamic raw,
  );

  @protected
  ProtonMeetAuthStore
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    dynamic raw,
  );

  @protected
  AppCore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    dynamic raw,
  );

  @protected
  FrbUserKeyProvider
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    dynamic raw,
  );

  @protected
  ProtonMeetAuthStore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    dynamic raw,
  );

  @protected
  FutureOr<String> Function(String)
  dco_decode_DartFn_Inputs_String_Output_String_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(String)
  dco_decode_DartFn_Inputs_String_Output_unit_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(String, String, int)
  dco_decode_DartFn_Inputs_String_String_u_32_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<String> Function(ChildAuthSession)
  dco_decode_DartFn_Inputs_child_auth_session_Output_String_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(MlsSyncState, RejoinReason?)
  dco_decode_DartFn_Inputs_mls_sync_state_opt_box_autoadd_rejoin_reason_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(RustLevel, String)
  dco_decode_DartFn_Inputs_rust_level_String_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw);

  @protected
  AppCore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    dynamic raw,
  );

  @protected
  FrbUserKeyProvider
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    dynamic raw,
  );

  @protected
  MeetCoreError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    dynamic raw,
  );

  @protected
  ProtonMeetAuthStore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    dynamic raw,
  );

  @protected
  RotatingFileWriter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<AppEvent> dco_decode_StreamSink_app_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Address dco_decode_address(dynamic raw);

  @protected
  AppEvent dco_decode_app_event(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MeetLink dco_decode_box_autoadd_meet_link(dynamic raw);

  @protected
  ProtonUser dco_decode_box_autoadd_proton_user(dynamic raw);

  @protected
  RecurrenceFrequency dco_decode_box_autoadd_recurrence_frequency(dynamic raw);

  @protected
  RejoinReason dco_decode_box_autoadd_rejoin_reason(dynamic raw);

  @protected
  ResponseError dco_decode_box_autoadd_response_error(dynamic raw);

  @protected
  ScheduleMeetingRequest dco_decode_box_autoadd_schedule_meeting_request(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  UserConfig dco_decode_box_autoadd_user_config(dynamic raw);

  @protected
  UserState dco_decode_box_autoadd_user_state(dynamic raw);

  @protected
  UserState dco_decode_box_user_state(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  ChildAuthSession dco_decode_child_auth_session(dynamic raw);

  @protected
  ConnectionState dco_decode_connection_state(dynamic raw);

  @protected
  EventAction dco_decode_event_action(dynamic raw);

  @protected
  FlutterLogLayer dco_decode_flutter_log_layer(dynamic raw);

  @protected
  FrbGetEventsResponse dco_decode_frb_get_events_response(dynamic raw);

  @protected
  FrbMeetInfo dco_decode_frb_meet_info(dynamic raw);

  @protected
  FrbMeetingEventItem dco_decode_frb_meeting_event_item(dynamic raw);

  @protected
  FrbMeetingInfo dco_decode_frb_meeting_info(dynamic raw);

  @protected
  FrbParticipantTrackSettings dco_decode_frb_participant_track_settings(
    dynamic raw,
  );

  @protected
  FrbUpcomingMeeting dco_decode_frb_upcoming_meeting(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  JoinType dco_decode_join_type(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Address> dco_decode_list_address(dynamic raw);

  @protected
  List<FrbMeetingEventItem> dco_decode_list_frb_meeting_event_item(dynamic raw);

  @protected
  List<FrbUpcomingMeeting> dco_decode_list_frb_upcoming_meeting(dynamic raw);

  @protected
  List<MeetParticipant> dco_decode_list_meet_participant(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProtonUserKey> dco_decode_list_proton_user_key(dynamic raw);

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw);

  @protected
  MeetChatMessage dco_decode_meet_chat_message(dynamic raw);

  @protected
  MeetLink dco_decode_meet_link(dynamic raw);

  @protected
  MeetParticipant dco_decode_meet_participant(dynamic raw);

  @protected
  MeetingType dco_decode_meeting_type(dynamic raw);

  @protected
  MlsSyncState dco_decode_mls_sync_state(dynamic raw);

  @protected
  Map<String, bool>? dco_decode_opt_Map_String_bool_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MeetLink? dco_decode_opt_box_autoadd_meet_link(dynamic raw);

  @protected
  RecurrenceFrequency? dco_decode_opt_box_autoadd_recurrence_frequency(
    dynamic raw,
  );

  @protected
  RejoinReason? dco_decode_opt_box_autoadd_rejoin_reason(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  UserState? dco_decode_opt_box_autoadd_user_state(dynamic raw);

  @protected
  List<FrbMeetingEventItem>? dco_decode_opt_list_frb_meeting_event_item(
    dynamic raw,
  );

  @protected
  List<ProtonUserKey>? dco_decode_opt_list_proton_user_key(dynamic raw);

  @protected
  ProtonUser dco_decode_proton_user(dynamic raw);

  @protected
  ProtonUserKey dco_decode_proton_user_key(dynamic raw);

  @protected
  ProtonUserSession dco_decode_proton_user_session(dynamic raw);

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  RecurrenceFrequency dco_decode_recurrence_frequency(dynamic raw);

  @protected
  RejoinReason dco_decode_rejoin_reason(dynamic raw);

  @protected
  ResponseError dco_decode_response_error(dynamic raw);

  @protected
  RustLevel dco_decode_rust_level(dynamic raw);

  @protected
  ScheduleMeetingRequest dco_decode_schedule_meeting_request(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnleashResponse dco_decode_unleash_response(dynamic raw);

  @protected
  UserConfig dco_decode_user_config(dynamic raw);

  @protected
  UserState dco_decode_user_state(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoMaxBitrate dco_decode_video_max_bitrate(dynamic raw);

  @protected
  VideoResolution dco_decode_video_resolution(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AppCore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    SseDeserializer deserializer,
  );

  @protected
  FrbUserKeyProvider
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    SseDeserializer deserializer,
  );

  @protected
  MeetCoreError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    SseDeserializer deserializer,
  );

  @protected
  ProtonMeetAuthStore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    SseDeserializer deserializer,
  );

  @protected
  RotatingFileWriter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    SseDeserializer deserializer,
  );

  @protected
  AppCore
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    SseDeserializer deserializer,
  );

  @protected
  FrbUserKeyProvider
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    SseDeserializer deserializer,
  );

  @protected
  ProtonMeetAuthStore
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    SseDeserializer deserializer,
  );

  @protected
  AppCore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    SseDeserializer deserializer,
  );

  @protected
  FrbUserKeyProvider
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    SseDeserializer deserializer,
  );

  @protected
  ProtonMeetAuthStore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    SseDeserializer deserializer,
  );

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  AppCore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    SseDeserializer deserializer,
  );

  @protected
  FrbUserKeyProvider
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    SseDeserializer deserializer,
  );

  @protected
  MeetCoreError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    SseDeserializer deserializer,
  );

  @protected
  ProtonMeetAuthStore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    SseDeserializer deserializer,
  );

  @protected
  RotatingFileWriter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AppEvent> sse_decode_StreamSink_app_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Address sse_decode_address(SseDeserializer deserializer);

  @protected
  AppEvent sse_decode_app_event(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MeetLink sse_decode_box_autoadd_meet_link(SseDeserializer deserializer);

  @protected
  ProtonUser sse_decode_box_autoadd_proton_user(SseDeserializer deserializer);

  @protected
  RecurrenceFrequency sse_decode_box_autoadd_recurrence_frequency(
    SseDeserializer deserializer,
  );

  @protected
  RejoinReason sse_decode_box_autoadd_rejoin_reason(
    SseDeserializer deserializer,
  );

  @protected
  ResponseError sse_decode_box_autoadd_response_error(
    SseDeserializer deserializer,
  );

  @protected
  ScheduleMeetingRequest sse_decode_box_autoadd_schedule_meeting_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  UserConfig sse_decode_box_autoadd_user_config(SseDeserializer deserializer);

  @protected
  UserState sse_decode_box_autoadd_user_state(SseDeserializer deserializer);

  @protected
  UserState sse_decode_box_user_state(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  ChildAuthSession sse_decode_child_auth_session(SseDeserializer deserializer);

  @protected
  ConnectionState sse_decode_connection_state(SseDeserializer deserializer);

  @protected
  EventAction sse_decode_event_action(SseDeserializer deserializer);

  @protected
  FlutterLogLayer sse_decode_flutter_log_layer(SseDeserializer deserializer);

  @protected
  FrbGetEventsResponse sse_decode_frb_get_events_response(
    SseDeserializer deserializer,
  );

  @protected
  FrbMeetInfo sse_decode_frb_meet_info(SseDeserializer deserializer);

  @protected
  FrbMeetingEventItem sse_decode_frb_meeting_event_item(
    SseDeserializer deserializer,
  );

  @protected
  FrbMeetingInfo sse_decode_frb_meeting_info(SseDeserializer deserializer);

  @protected
  FrbParticipantTrackSettings sse_decode_frb_participant_track_settings(
    SseDeserializer deserializer,
  );

  @protected
  FrbUpcomingMeeting sse_decode_frb_upcoming_meeting(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  JoinType sse_decode_join_type(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Address> sse_decode_list_address(SseDeserializer deserializer);

  @protected
  List<FrbMeetingEventItem> sse_decode_list_frb_meeting_event_item(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbUpcomingMeeting> sse_decode_list_frb_upcoming_meeting(
    SseDeserializer deserializer,
  );

  @protected
  List<MeetParticipant> sse_decode_list_meet_participant(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProtonUserKey> sse_decode_list_proton_user_key(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  );

  @protected
  MeetChatMessage sse_decode_meet_chat_message(SseDeserializer deserializer);

  @protected
  MeetLink sse_decode_meet_link(SseDeserializer deserializer);

  @protected
  MeetParticipant sse_decode_meet_participant(SseDeserializer deserializer);

  @protected
  MeetingType sse_decode_meeting_type(SseDeserializer deserializer);

  @protected
  MlsSyncState sse_decode_mls_sync_state(SseDeserializer deserializer);

  @protected
  Map<String, bool>? sse_decode_opt_Map_String_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MeetLink? sse_decode_opt_box_autoadd_meet_link(SseDeserializer deserializer);

  @protected
  RecurrenceFrequency? sse_decode_opt_box_autoadd_recurrence_frequency(
    SseDeserializer deserializer,
  );

  @protected
  RejoinReason? sse_decode_opt_box_autoadd_rejoin_reason(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  UserState? sse_decode_opt_box_autoadd_user_state(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbMeetingEventItem>? sse_decode_opt_list_frb_meeting_event_item(
    SseDeserializer deserializer,
  );

  @protected
  List<ProtonUserKey>? sse_decode_opt_list_proton_user_key(
    SseDeserializer deserializer,
  );

  @protected
  ProtonUser sse_decode_proton_user(SseDeserializer deserializer);

  @protected
  ProtonUserKey sse_decode_proton_user_key(SseDeserializer deserializer);

  @protected
  ProtonUserSession sse_decode_proton_user_session(
    SseDeserializer deserializer,
  );

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  RecurrenceFrequency sse_decode_recurrence_frequency(
    SseDeserializer deserializer,
  );

  @protected
  RejoinReason sse_decode_rejoin_reason(SseDeserializer deserializer);

  @protected
  ResponseError sse_decode_response_error(SseDeserializer deserializer);

  @protected
  RustLevel sse_decode_rust_level(SseDeserializer deserializer);

  @protected
  ScheduleMeetingRequest sse_decode_schedule_meeting_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnleashResponse sse_decode_unleash_response(SseDeserializer deserializer);

  @protected
  UserConfig sse_decode_user_config(SseDeserializer deserializer);

  @protected
  UserState sse_decode_user_state(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoMaxBitrate sse_decode_video_max_bitrate(SseDeserializer deserializer);

  @protected
  VideoResolution sse_decode_video_resolution(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    AppCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    FrbUserKeyProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    MeetCoreError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    ProtonMeetAuthStore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    RotatingFileWriter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    AppCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    FrbUserKeyProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    ProtonMeetAuthStore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    AppCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    FrbUserKeyProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    ProtonMeetAuthStore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_Output_String_AnyhowException(
    FutureOr<String> Function(String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_String_u_32_Output_unit_AnyhowException(
    FutureOr<void> Function(String, String, int) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_child_auth_session_Output_String_AnyhowException(
    FutureOr<String> Function(ChildAuthSession) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_mls_sync_state_opt_box_autoadd_rejoin_reason_Output_unit_AnyhowException(
    FutureOr<void> Function(MlsSyncState, RejoinReason?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_rust_level_String_Output_unit_AnyhowException(
    FutureOr<void> Function(RustLevel, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    AppCore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    FrbUserKeyProvider self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    MeetCoreError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    ProtonMeetAuthStore self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    RotatingFileWriter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_app_event_Sse(
    RustStreamSink<AppEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address(Address self, SseSerializer serializer);

  @protected
  void sse_encode_app_event(AppEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_meet_link(
    MeetLink self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_proton_user(
    ProtonUser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_recurrence_frequency(
    RecurrenceFrequency self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rejoin_reason(
    RejoinReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_response_error(
    ResponseError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_schedule_meeting_request(
    ScheduleMeetingRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_config(
    UserConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_user_state(
    UserState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_user_state(UserState self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_child_auth_session(
    ChildAuthSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_state(
    ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_event_action(EventAction self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_log_layer(
    FlutterLogLayer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_get_events_response(
    FrbGetEventsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_meet_info(FrbMeetInfo self, SseSerializer serializer);

  @protected
  void sse_encode_frb_meeting_event_item(
    FrbMeetingEventItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_meeting_info(
    FrbMeetingInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_participant_track_settings(
    FrbParticipantTrackSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_upcoming_meeting(
    FrbUpcomingMeeting self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_join_type(JoinType self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_address(List<Address> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_meeting_event_item(
    List<FrbMeetingEventItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_upcoming_meeting(
    List<FrbUpcomingMeeting> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meet_participant(
    List<MeetParticipant> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proton_user_key(
    List<ProtonUserKey> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meet_chat_message(
    MeetChatMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meet_link(MeetLink self, SseSerializer serializer);

  @protected
  void sse_encode_meet_participant(
    MeetParticipant self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meeting_type(MeetingType self, SseSerializer serializer);

  @protected
  void sse_encode_mls_sync_state(MlsSyncState self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_bool_None(
    Map<String, bool>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_meet_link(
    MeetLink? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_recurrence_frequency(
    RecurrenceFrequency? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rejoin_reason(
    RejoinReason? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_state(
    UserState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_frb_meeting_event_item(
    List<FrbMeetingEventItem>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_proton_user_key(
    List<ProtonUserKey>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proton_user(ProtonUser self, SseSerializer serializer);

  @protected
  void sse_encode_proton_user_key(ProtonUserKey self, SseSerializer serializer);

  @protected
  void sse_encode_proton_user_session(
    ProtonUserSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_u_64(
    (String, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recurrence_frequency(
    RecurrenceFrequency self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rejoin_reason(RejoinReason self, SseSerializer serializer);

  @protected
  void sse_encode_response_error(ResponseError self, SseSerializer serializer);

  @protected
  void sse_encode_rust_level(RustLevel self, SseSerializer serializer);

  @protected
  void sse_encode_schedule_meeting_request(
    ScheduleMeetingRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unleash_response(
    UnleashResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_config(UserConfig self, SseSerializer serializer);

  @protected
  void sse_encode_user_state(UserState self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_max_bitrate(
    VideoMaxBitrate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_video_resolution(
    VideoResolution self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppCore(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrbUserKeyProvider(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMeetCoreError(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProtonMeetAuthStore(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRotatingFileWriter(
    int ptr,
  );
}
