// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_file_size`, `generate_rotated_file_name`, `open_log_file`, `rotate_log_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LOG_GUARD`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `flush`, `initialize`, `make_writer`, `write`

void initRustLogging({
  required String filePath,
  required String fileName,
  required bool flutterLayer,
}) => RustLib.instance.api.crateLoggerInitRustLogging(
  filePath: filePath,
  fileName: fileName,
  flutterLayer: flutterLayer,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RotatingFileWriter>>
abstract class RotatingFileWriter implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RotatingFileWriter> newInstance({
    required String fileFolder,
    required String fileName,
  }) => RustLib.instance.api.crateLoggerRotatingFileWriterNew(
    fileFolder: fileFolder,
    fileName: fileName,
  );
}
