// Mocks generated by Mockito 5.4.6 from annotations
// in meet/test/mocks/user.agent.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:device_info_plus/device_info_plus.dart' as _i2;
import 'package:meet/helper/user.agent.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:package_info_plus/package_info_plus.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeviceInfoPlugin_0 extends _i1.SmartFake
    implements _i2.DeviceInfoPlugin {
  _FakeDeviceInfoPlugin_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePackageInfo_1 extends _i1.SmartFake implements _i3.PackageInfo {
  _FakePackageInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserAgent].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserAgent extends _i1.Mock implements _i4.UserAgent {
  MockUserAgent() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceInfoPlugin get deviceInfo =>
      (super.noSuchMethod(
            Invocation.getter(#deviceInfo),
            returnValue: _FakeDeviceInfoPlugin_0(
              this,
              Invocation.getter(#deviceInfo),
            ),
          )
          as _i2.DeviceInfoPlugin);

  @override
  _i5.Future<_i3.PackageInfo> get packageInfo =>
      (super.noSuchMethod(
            Invocation.getter(#packageInfo),
            returnValue: _i5.Future<_i3.PackageInfo>.value(
              _FakePackageInfo_1(this, Invocation.getter(#packageInfo)),
            ),
          )
          as _i5.Future<_i3.PackageInfo>);

  @override
  _i5.Future<String> get ua =>
      (super.noSuchMethod(
            Invocation.getter(#ua),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.getter(#ua)),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> get appVersion =>
      (super.noSuchMethod(
            Invocation.getter(#appVersion),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.getter(#appVersion)),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> get display =>
      (super.noSuchMethod(
            Invocation.getter(#display),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.getter(#display)),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> get displayWithoutName =>
      (super.noSuchMethod(
            Invocation.getter(#displayWithoutName),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.getter(#displayWithoutName),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> get sentryRelease =>
      (super.noSuchMethod(
            Invocation.getter(#sentryRelease),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.getter(#sentryRelease)),
            ),
          )
          as _i5.Future<String>);

  @override
  set deviceInfo(_i2.DeviceInfoPlugin? value) => super.noSuchMethod(
    Invocation.setter(#deviceInfo, value),
    returnValueForMissingStub: null,
  );

  @override
  set packageInfo(_i5.Future<_i3.PackageInfo>? value) => super.noSuchMethod(
    Invocation.setter(#packageInfo, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String> getAppNameAndVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getAppNameAndVersion, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAppNameAndVersion, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getDeviceVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceVersion, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getDeviceVersion, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getDeviceName() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceName, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getDeviceName, []),
              ),
            ),
          )
          as _i5.Future<String>);
}
